name: Sahlqvist-Calculator
version: 1.1.3
github: "https://github.com/SinnuOu/Sahlqvist-Calculator"
license: GPL-3.0
author: "WANG, Xinyu"
maintainer: "s2010404@jaist.ac.jp"
copyright: "2020 WANG, Xinyu"
extra-source-files:
- c_src/c_parseM.h
- c_src/c_parseM.l
- c_src/c_parseM.y
- README.md
- ChangeLog.md
- Makefile
description: Please see the ReadMe on GitHub at <https://github.com/SinnuOu/Sahlqvist-Calculator/blob/main/README.md>.
dependencies:
- base
- containers
- gi-gtk
- haskell-gi-base
- text
library:
  source-dirs: src
  c-sources:
  - c_src/lex.yy.c
  - c_src/c_parseM.tab.c
  include-dirs: c_src
executables:
  Sahlqvist-Calculator:
    main: Main.hs
    source-dirs: app
    dependencies: Sahlqvist-Calculator